language: python
python:
  - "2.7"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements-dev.txt
# command to run tests
script:
  - make tests
  - travis-sphinx --nowarn --source=docs build

after_success:
    - travis-sphinx deploy
