language: python
python:
    - "2.7"
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"
    - "nightly"
matrix:
    fast_finish: true
    allow_failures:
        - python: "3.6-dev"
        - python: "3.7-dev"
        - python: "nightly"
install:
    - pip install .[tf]
    - pip install -r requirements/docs.txt
    - pip install -r requirements/test.txt
script:
    - pytest --cov=decotools decotools
    - flake8 decotools
    - bash ci/build_docs.sh
after_success:
    - pip install codecov
    - codecov
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/_build/html
    target_branch: gh-pages
    email: "github-pages-deploy@travis-ci.org"
    on:
        branch: master
        python: "2.7"
