site_name: decotools
site_description: DECO toolset
theme: cinder
pages:
    - Home: index.md
    - API:
        - 'File I/O': fileio.md
        - 'Blob Detection': blobdetection.md
    - Contributing: contributing.md

repo_name: 'GitHub'
repo_url: https://github.com/mattmeehan/decotools

markdown_extensions:
  - codehilite
  - toc(permalink=false)
