site_name: decotools
site_description: DECO toolset
# site_dir: ../docs
theme: cinder
pages:
    - Home: index.md
repo_name: 'GitHub'
repo_url: https://github.com/mattmeehan/decotools

markdown_extensions:
  - codehilite
  - toc(permalink=true)
